import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

// GitHub's own sidebar appears around 768px and takes roughly 300px out of the
// README column, so a 760px breakpoint handed the widest asset to the narrowest
// usable column: at a 800px viewport the desktop hero rendered at 0.364 scale,
// worse than on a phone. The switch has to clear the whole narrow-column band.
const NARROW = "(max-width: 1100px)";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

// Text links, not badge images. The shields.io badges that used to live here
// were the only third-party network requests on the page, and they sat
// directly above this README's own claim of using no third-party service.
//
// Anchors rather than Markdown link syntax: this sits inside a
// <p align="center"> on the same line, which GFM treats as a raw HTML block
// and passes through unparsed, so [label](url) would render literally.
function renderLinks(links) {
  return links
    .map((link) => `<a href="${escapeHtml(link.url)}">${escapeHtml(link.label)}</a>`)
    .join(" · ");
}

function renderFocus(focus) {
  return [
    "| Area | What I am exploring |",
    "| --- | --- |",
    ...focus.map((item) => `| **${escapeCell(item.name)}** | ${escapeCell(item.description)} |`)
  ].join("\n");
}

function renderProjects(projects) {
  return [
    "| Project | Focus | Why it matters |",
    "| --- | --- | --- |",
    ...projects.map((project) => {
      const homepage = project.homepage ? ` [Live](${project.homepage})` : "";
      return `| [**${escapeCell(project.name)}**](${project.url}) | ${escapeCell(project.focus)} | ${escapeCell(project.summary)}${homepage} |`;
    })
  ].join("\n");
}

function renderContributionConsole(manifest, profileName) {
  if (!manifest?.assets?.dark || !manifest?.assets?.light) return "";
  const total = Number(manifest.stats?.total || 0).toLocaleString("en");
  const active = Number(manifest.stats?.activeDays || 0);
  const { dark, light, mobileDark, mobileLight } = manifest.assets;
  const narrow = mobileDark && mobileLight
    ? `    <source media="${NARROW} and (prefers-color-scheme: dark)" srcset="./assets/activity/${mobileDark}">\n` +
      `    <source media="${NARROW}" srcset="./assets/activity/${mobileLight}">\n`
    : "";
  return `
## Build Activity

<p align="center">
  <picture>
${narrow}    <source media="(prefers-color-scheme: dark)" srcset="./assets/activity/${dark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/activity/${light}">
    <img src="./assets/activity/${dark}" alt="${profileName} public GitHub activity: ${total} contributions across ${active} active days" width="100%">
  </picture>
</p>

<p align="center"><sub>Generated from public GitHub activity and refreshed automatically—no third-party stats service.</sub></p>`;
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

export async function generateProfileReadme({ config, manifest, contributionManifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const techStack = config.techStack.map((item) => `\`${item}\``).join(" · ");
  const about = config.profile.about.join("\n\n");
  const contributionSection = config.activity.enabled ? renderContributionConsole(contributionManifest, config.profile.name) : "";

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <picture>
    <source media="${NARROW} and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="${NARROW}" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<p align="center">${renderLinks(config.links)}</p>
${contributionSection}

## About Me

${about}

## Current Focus

${renderFocus(config.focus)}

## Featured Work

${renderProjects(config.projects)}

## Product Direction

${config.research.narrative}

## Tech Stack

${techStack}
${activitySection}
---

<p align="center">
  ${config.footer}
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
